use MER5;
SELECT CLIENT.Nom, VEHICLE.Marca, TIPUS_VEHICLE.Nom, CITA.Data_cita, CITA.Lloc, CLIENT_VEHICLE.Data_darrera_revisio
FROM CLIENT, VEHICLE, TIPUS_VEHICLE, CITA, CLIENT_VEHICLE
WHERE CLIENT.DNI=CLIENT_VEHICLE.CLIENT_DNI AND
		VEHICLE.Num_bastidor=CLIENT_VEHICLE.VEHICLE_Num_bastidor AND
        TIPUS_VEHICLE.ID=VEHICLE.TIPUS_VEHICLE_ID AND
        CLIENT_VEHICLE.ID=CITA.CLIENT_VEHICLE_ID;